<?php

namespace Database\Factories;

use App\Enums\Priority;
use App\Enums\RequestCategory;
use App\Enums\RequestStatus;
use App\Models\Client;
use App\Models\ServiceRequest;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<ServiceRequest>
 */
class ServiceRequestFactory extends Factory
{
    protected $model = ServiceRequest::class;

    public function definition(): array
    {
        return [
            // request_number is auto-generated by the model's creating hook.
            'client_id' => Client::factory(),
            'project_id' => null,
            'title' => fake()->sentence(4),
            'description' => fake()->paragraph(),
            'category' => fake()->randomElement(RequestCategory::cases()),
            'priority' => fake()->randomElement(Priority::cases()),
            'assigned_to' => null,
            'status' => fake()->randomElement(RequestStatus::cases()),
            'due_date' => fake()->dateTimeBetween('now', '+30 days'),
            'created_by' => null,
        ];
    }
}
